chore: fix pre-commit hook

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -14,36 +14,28 @@ if ! [ -x "$(command -v mvn)" ]; then
   exit 1
 fi
 
-spotless() {
-  if [ ! -e "mvn" ]; then
+if [ ! -e "mvn" ]; then
     return 0
-  fi
+fi
 
-  CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.xml?$/ { print $NF }')"
+CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.xml?$/ { print $NF }')"
 
-  if [ -z "$CHANGED_FILES" ]; then
-    echo "No staged files."
-    return 0
-  fi
+if [ -z "$CHANGED_FILES" ]; then
+  echo "No staged files."
+  return 0
+fi
 
-  echo '[pre-commit] Executing Maven spotlessCheck before commit'
+echo '[pre-commit] Executing Maven spotlessCheck before commit'
 
-  git stash --quiet --keep-index
+git stash --quiet --keep-index
 
-  mvn -B spotless:check
+mvn spotless:check -DspotlessFiles=$CHANGED_FILES
 
-  RESULT=$?
+RESULT=$?
 
-  git stash pop -q
+git stash pop -q
 
-  if [ "$RESULT" -ne "0" ]; then
-    echo -e "spotlessCheck failed..."
-    echo -e 'You can try "./mvn spotless:apply" to apply auto-fixes.'
-  fi
-
-  return $RESULT
-}
-
-if ! spotless; then
-  exit 1
+if [ "$RESULT" -ne "0" ]; then
+  echo -e "spotlessCheck failed..."
+  echo -e 'You can try "./mvn spotless:apply" to apply auto-fixes.'
 fi
